const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AJAX,
		C3.Plugins.ppstudio_lolapi,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Timeline,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Behaviors.Fade,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Plugins.Text,
		C3.Behaviors.Flash,
		C3.Behaviors.Pin,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Behaviors.Bullet,
		C3.Behaviors.wrap,
		C3.Behaviors.solid,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.ppstudio_lolapi.Acts.LoadState,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.ppstudio_lolapi.Acts.GameIsReady,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.ppstudio_lolapi.Acts.Mute,
		C3.Plugins.ppstudio_lolapi.Acts.Unmute,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.ppstudio_lolapi.Cnds.Pause,
		C3.Plugins.ppstudio_lolapi.Acts.Suspend,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Timeline.Cnds.IsPlayingByTags,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Timeline.Cnds.OnTimelineFinishedByTags,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.ppstudio_lolapi.Acts.AutoProgress,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.ppstudio_lolapi.Acts.SaveState,
		C3.Plugins.ppstudio_lolapi.Exps.GetStateData,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.ppstudio_lolapi.Acts.SetMaxProgress,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.ppstudio_lolapi.Acts.SpeakText,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.ppstudio_lolapi.Exps.GetRawText,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Acts.SetLayerEffectEnabled,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.LayerInteractive,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.EightDir.Acts.SetIgnoreInput,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Timeline.Acts.ResumeTimelineByTags,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Timeline.Acts.StopTimelineByTags,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.ppstudio_lolapi.Acts.CompleteGame,
		C3.Plugins.Audio.Acts.Stop
	];
};
self.C3_JsPropNameTable = [
	{AJAX: 0},
	{LoLAPI: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{Audio: 0},
	{Browser: 0},
	{LocalStorage: 0},
	{Touch: 0},
	{TimelineController: 0},
	{reiniciando: 0},
	{btn_Reset: 0},
	{btn_Mute: 0},
	{Sine: 0},
	{Tween: 0},
	{btn_Next: 0},
	{Fade: 0},
	{fade: 0},
	{fondoTexto: 0},
	{particulaEstrella: 0},
	{rate: 0},
	{Rotate: 0},
	{confeti: 0},
	{TextGame: 0},
	{ParticlesConfeti: 0},
	{TextBtnNew: 0},
	{TextBtnContinue: 0},
	{tips: 0},
	{btn_Idea: 0},
	{vidas: 0},
	{FondoBarraEnergiaBarco: 0},
	{Flash: 0},
	{barraEnergiaBarco: 0},
	{fadeIntro: 0},
	{logo: 0},
	{jump: 0},
	{Pin: 0},
	{sombraPlayer: 0},
	{run: 0},
	{climb: 0},
	{bomba: 0},
	{tocarGrieta: 0},
	{"8Direction": 0},
	{BoundToLayout: 0},
	{Player: 0},
	{titulo: 0},
	{btn_Play: 0},
	{btn_Load: 0},
	{castillo: 0},
	{oceanoMenu: 0},
	{barcoMenu: 0},
	{rocaAdornoMenu: 0},
	{barcoLvL1: 0},
	{tablas90: 0},
	{banderaPirataBarcoLvL1: 0},
	{taparCanon: 0},
	{tablasUltimoBarco: 0},
	{cieloLvL1: 0},
	{Bullet: 0},
	{Wrap: 0},
	{nubesLvL1: 0},
	{aguaLvL1: 0},
	{arenaLvL1: 0},
	{montanaLvL1: 0},
	{plantasSombrasLvL1: 0},
	{palmeraLvL1: 0},
	{aguaBajoBarcoLvL1: 0},
	{teclasControl: 0},
	{Solid: 0},
	{colisionPlayaLvl1: 0},
	{tapar: 0},
	{ArenaTapaBomba: 0},
	{cangrejo: 0},
	{canon10x: 0},
	{canon1x: 0},
	{canon100X: 0},
	{canon1000X: 0},
	{canon1xB: 0},
	{canon10xB: 0},
	{canon100xB: 0},
	{canonDiv10: 0},
	{canonDiv100: 0},
	{canonDiv1000: 0},
	{canonDiv100B: 0},
	{obtenida: 0},
	{bomba9: 0},
	{bomba4: 0},
	{bomba8: 0},
	{sombraBomba8: 0},
	{sombraBomba9: 0},
	{sombraBomba4: 0},
	{bomba2: 0},
	{sombraBomba2: 0},
	{bomba3: 0},
	{sombraBomba3: 0},
	{bomba5: 0},
	{sombraBomba5: 0},
	{bomba7: 0},
	{sombraBomba7: 0},
	{bomba6: 0},
	{sombraBomba6: 0},
	{bomba1: 0},
	{sombraBomba1: 0},
	{bomba20: 0},
	{sombraBomba20: 0},
	{bomba30: 0},
	{sombraBomba30: 0},
	{bomba50: 0},
	{sombraBomba50: 0},
	{bomba80: 0},
	{sombraBomba80: 0},
	{bomba70: 0},
	{sombraBomba70: 0},
	{bomba40: 0},
	{sombraBomba40: 0},
	{bomba90: 0},
	{sombraBomba90: 0},
	{bomba60: 0},
	{sombraBomba60: 0},
	{bomba10: 0},
	{sombraBomba10: 0},
	{bomba200: 0},
	{bomba500: 0},
	{sombraBomba500: 0},
	{sombraBomba200: 0},
	{bomba400: 0},
	{sombraBomba400: 0},
	{bomba900: 0},
	{sombraBomba900: 0},
	{bomba600: 0},
	{sombraBomba600: 0},
	{bomba800: 0},
	{sombraBomba800: 0},
	{bomba100: 0},
	{sombraBomba100: 0},
	{bomba700: 0},
	{sombraBomba700: 0},
	{bomba300: 0},
	{sombraBomba300: 0},
	{bomba4000: 0},
	{sombraBomba4000: 0},
	{bomba9000: 0},
	{sombraBomba9000: 0},
	{bomba6000: 0},
	{sombraBomba6000: 0},
	{bomba2000: 0},
	{sombraBomba2000: 0},
	{bomba3000: 0},
	{sombraBomba3000: 0},
	{bomba8000: 0},
	{sombraBomba8000: 0},
	{bomba5000: 0},
	{sombraBomba5000: 0},
	{bomba1000: 0},
	{sombraBomba1000: 0},
	{Tips9x1: 0},
	{explosionBarco: 0},
	{explosionCanon: 0},
	{bombaCanon: 0},
	{explosionCompuertasBarco: 0},
	{bombaCanon2: 0},
	{bombaCanon3: 0},
	{bombaCanon4: 0},
	{cieloLvL3: 0},
	{luna: 0},
	{marDeFondoLvL3: 0},
	{lineaHorizonteMarDeFondoLvL3: 0},
	{islasLvL3: 0},
	{pisoLvL34: 0},
	{estrellas: 0},
	{gritasBarco: 0},
	{bombaBarco: 0},
	{bote: 0},
	{lanzaBote: 0},
	{explosionLanza: 0},
	{TibuBucle: 0},
	{tiburon: 0},
	{tiburon2: 0},
	{Sine2: 0},
	{tiburonMenu: 0},
	{cieloLvL5: 0},
	{palmerasLvL5: 0},
	{nubesHorizonteLvL5: 0},
	{solLvL5: 0},
	{reloj: 0},
	{pisoDerechoActivado: 0},
	{pisoPilarIzq: 0},
	{pisoIzquierdoActivado: 0},
	{pisoPilarDer: 0},
	{agarrada: 0},
	{pilarIzquierdo: 0},
	{pilarIDerecho: 0},
	{intro: 0},
	{colisionesPlayer: 0},
	{colisionesAbajoCanon: 0},
	{soundBtn: 0},
	{bombas: 0},
	{canones: 0},
	{Save: 0},
	{mute: 0}
];

self.InstanceType = {
	AJAX: class extends self.IInstance {},
	LoLAPI: class extends self.C3.Plugins.ppstudio_lolapi.Instance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	TimelineController: class extends self.IInstance {},
	btn_Reset: class extends self.ISpriteInstance {},
	btn_Mute: class extends self.ISpriteInstance {},
	btn_Next: class extends self.ISpriteInstance {},
	fade: class extends self.ITiledBackgroundInstance {},
	fondoTexto: class extends self.ISpriteInstance {},
	particulaEstrella: class extends self.IParticlesInstance {},
	rate: class extends self.ISpriteInstance {},
	confeti: class extends self.ISpriteInstance {},
	TextGame: class extends self.ITextInstance {},
	ParticlesConfeti: class extends self.IParticlesInstance {},
	TextBtnNew: class extends self.ITextInstance {},
	TextBtnContinue: class extends self.ITextInstance {},
	btn_Idea: class extends self.ISpriteInstance {},
	vidas: class extends self.ISpriteInstance {},
	FondoBarraEnergiaBarco: class extends self.ISpriteInstance {},
	barraEnergiaBarco: class extends self.ISpriteInstance {},
	fadeIntro: class extends self.ITiledBackgroundInstance {},
	logo: class extends self.ISpriteInstance {},
	sombraPlayer: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	titulo: class extends self.ISpriteInstance {},
	btn_Play: class extends self.ISpriteInstance {},
	btn_Load: class extends self.ISpriteInstance {},
	castillo: class extends self.ISpriteInstance {},
	oceanoMenu: class extends self.ISpriteInstance {},
	barcoMenu: class extends self.ISpriteInstance {},
	rocaAdornoMenu: class extends self.ISpriteInstance {},
	barcoLvL1: class extends self.ISpriteInstance {},
	tablas90: class extends self.ISpriteInstance {},
	banderaPirataBarcoLvL1: class extends self.ISpriteInstance {},
	taparCanon: class extends self.ISpriteInstance {},
	tablasUltimoBarco: class extends self.ISpriteInstance {},
	cieloLvL1: class extends self.ITiledBackgroundInstance {},
	nubesLvL1: class extends self.ISpriteInstance {},
	aguaLvL1: class extends self.ISpriteInstance {},
	arenaLvL1: class extends self.ISpriteInstance {},
	montanaLvL1: class extends self.ISpriteInstance {},
	plantasSombrasLvL1: class extends self.ISpriteInstance {},
	palmeraLvL1: class extends self.ISpriteInstance {},
	aguaBajoBarcoLvL1: class extends self.ISpriteInstance {},
	teclasControl: class extends self.ISpriteInstance {},
	colisionPlayaLvl1: class extends self.ISpriteInstance {},
	ArenaTapaBomba: class extends self.ISpriteInstance {},
	cangrejo: class extends self.ISpriteInstance {},
	canon10x: class extends self.ISpriteInstance {},
	canon1x: class extends self.ISpriteInstance {},
	canon100X: class extends self.ISpriteInstance {},
	canon1000X: class extends self.ISpriteInstance {},
	canon1xB: class extends self.ISpriteInstance {},
	canon10xB: class extends self.ISpriteInstance {},
	canon100xB: class extends self.ISpriteInstance {},
	canonDiv10: class extends self.ISpriteInstance {},
	canonDiv100: class extends self.ISpriteInstance {},
	canonDiv1000: class extends self.ISpriteInstance {},
	canonDiv100B: class extends self.ISpriteInstance {},
	bomba9: class extends self.ISpriteInstance {},
	bomba4: class extends self.ISpriteInstance {},
	bomba8: class extends self.ISpriteInstance {},
	sombraBomba8: class extends self.ISpriteInstance {},
	sombraBomba9: class extends self.ISpriteInstance {},
	sombraBomba4: class extends self.ISpriteInstance {},
	bomba2: class extends self.ISpriteInstance {},
	sombraBomba2: class extends self.ISpriteInstance {},
	bomba3: class extends self.ISpriteInstance {},
	sombraBomba3: class extends self.ISpriteInstance {},
	bomba5: class extends self.ISpriteInstance {},
	sombraBomba5: class extends self.ISpriteInstance {},
	bomba7: class extends self.ISpriteInstance {},
	sombraBomba7: class extends self.ISpriteInstance {},
	bomba6: class extends self.ISpriteInstance {},
	sombraBomba6: class extends self.ISpriteInstance {},
	bomba1: class extends self.ISpriteInstance {},
	sombraBomba1: class extends self.ISpriteInstance {},
	bomba20: class extends self.ISpriteInstance {},
	sombraBomba20: class extends self.ISpriteInstance {},
	bomba30: class extends self.ISpriteInstance {},
	sombraBomba30: class extends self.ISpriteInstance {},
	bomba50: class extends self.ISpriteInstance {},
	sombraBomba50: class extends self.ISpriteInstance {},
	bomba80: class extends self.ISpriteInstance {},
	sombraBomba80: class extends self.ISpriteInstance {},
	bomba70: class extends self.ISpriteInstance {},
	sombraBomba70: class extends self.ISpriteInstance {},
	bomba40: class extends self.ISpriteInstance {},
	sombraBomba40: class extends self.ISpriteInstance {},
	bomba90: class extends self.ISpriteInstance {},
	sombraBomba90: class extends self.ISpriteInstance {},
	bomba60: class extends self.ISpriteInstance {},
	sombraBomba60: class extends self.ISpriteInstance {},
	bomba10: class extends self.ISpriteInstance {},
	sombraBomba10: class extends self.ISpriteInstance {},
	bomba200: class extends self.ISpriteInstance {},
	bomba500: class extends self.ISpriteInstance {},
	sombraBomba500: class extends self.ISpriteInstance {},
	sombraBomba200: class extends self.ISpriteInstance {},
	bomba400: class extends self.ISpriteInstance {},
	sombraBomba400: class extends self.ISpriteInstance {},
	bomba900: class extends self.ISpriteInstance {},
	sombraBomba900: class extends self.ISpriteInstance {},
	bomba600: class extends self.ISpriteInstance {},
	sombraBomba600: class extends self.ISpriteInstance {},
	bomba800: class extends self.ISpriteInstance {},
	sombraBomba800: class extends self.ISpriteInstance {},
	bomba100: class extends self.ISpriteInstance {},
	sombraBomba100: class extends self.ISpriteInstance {},
	bomba700: class extends self.ISpriteInstance {},
	sombraBomba700: class extends self.ISpriteInstance {},
	bomba300: class extends self.ISpriteInstance {},
	sombraBomba300: class extends self.ISpriteInstance {},
	bomba4000: class extends self.ISpriteInstance {},
	sombraBomba4000: class extends self.ISpriteInstance {},
	bomba9000: class extends self.ISpriteInstance {},
	sombraBomba9000: class extends self.ISpriteInstance {},
	bomba6000: class extends self.ISpriteInstance {},
	sombraBomba6000: class extends self.ISpriteInstance {},
	bomba2000: class extends self.ISpriteInstance {},
	sombraBomba2000: class extends self.ISpriteInstance {},
	bomba3000: class extends self.ISpriteInstance {},
	sombraBomba3000: class extends self.ISpriteInstance {},
	bomba8000: class extends self.ISpriteInstance {},
	sombraBomba8000: class extends self.ISpriteInstance {},
	bomba5000: class extends self.ISpriteInstance {},
	sombraBomba5000: class extends self.ISpriteInstance {},
	bomba1000: class extends self.ISpriteInstance {},
	sombraBomba1000: class extends self.ISpriteInstance {},
	Tips9x1: class extends self.ISpriteInstance {},
	explosionBarco: class extends self.ISpriteInstance {},
	explosionCanon: class extends self.ISpriteInstance {},
	bombaCanon: class extends self.ISpriteInstance {},
	explosionCompuertasBarco: class extends self.ISpriteInstance {},
	bombaCanon2: class extends self.ISpriteInstance {},
	bombaCanon3: class extends self.ISpriteInstance {},
	bombaCanon4: class extends self.ISpriteInstance {},
	cieloLvL3: class extends self.ITiledBackgroundInstance {},
	luna: class extends self.ISpriteInstance {},
	marDeFondoLvL3: class extends self.ITiledBackgroundInstance {},
	lineaHorizonteMarDeFondoLvL3: class extends self.ISpriteInstance {},
	islasLvL3: class extends self.ISpriteInstance {},
	pisoLvL34: class extends self.ISpriteInstance {},
	estrellas: class extends self.ISpriteInstance {},
	gritasBarco: class extends self.ISpriteInstance {},
	bombaBarco: class extends self.ISpriteInstance {},
	bote: class extends self.ISpriteInstance {},
	lanzaBote: class extends self.ISpriteInstance {},
	explosionLanza: class extends self.ISpriteInstance {},
	tiburon: class extends self.ISpriteInstance {},
	tiburon2: class extends self.ISpriteInstance {},
	tiburonMenu: class extends self.ISpriteInstance {},
	cieloLvL5: class extends self.ITiledBackgroundInstance {},
	palmerasLvL5: class extends self.ISpriteInstance {},
	nubesHorizonteLvL5: class extends self.ISpriteInstance {},
	solLvL5: class extends self.ISpriteInstance {},
	pisoPilarIzq: class extends self.ISpriteInstance {},
	pisoPilarDer: class extends self.ISpriteInstance {},
	pilarIzquierdo: class extends self.ISpriteInstance {},
	pilarIDerecho: class extends self.ISpriteInstance {},
	intro: class extends self.ISpriteInstance {},
	colisionesPlayer: class extends self.ITiledBackgroundInstance {},
	colisionesAbajoCanon: class extends self.ITiledBackgroundInstance {},
	soundBtn: class extends self.ISpriteInstance {},
	bombas: class extends self.ISpriteInstance {},
	canones: class extends self.ISpriteInstance {}
}